grpc:
  port: 8080
  host: 0.0.0.0
  request_timeout: 20

graphql:
  port: 8081
  host: 0.0.0.0
  request_Timeout: 20

rest:
  port: 8082
  host: 0.0.0.0
  request_timeout: 20

health_check:
  port: 8083
  host: 0.0.0.0

cadence_config:
  domain: simple-domain
  port: 7933
  host: 0.0.0.0
  service: cadence-frontend

promthesius:
  port: 8084
  host: 0.0.0.0

logger:
  log_level: -1

mongo:
  host: mongodb://127.0.0.1
  port: 27017
  db_name: your

postgres:
  host: localhost
  port: 5432
  user: your_usr
  password: your_User
  db_name: your
  ssl_mode: true
  pg_driver: pgx

metrics:
  url: 0.0.0.0:7070
  service_name: your_Metrics

jaeger:
  host: 0.0.0.0
  port: 6831
  service_name: your_Tracing
  log_spans: false

auth0:
  auth0_client_id: BFnfdaibKSdqkSAOksr3XuUNJuCW9zbZ
  auth0_domain: your_-sh.br.auth0.com
  auth0_client_secret: e6JJn1cKSEHk8p1FuoBdDbhmWWINevDitFBsWMTkZi8BbL8AVTQlLfgkwSCyyqJX
  auth0_call_back_url: http://localhost:3000/authentication/callback

auth:
  secret: e6JJn1cKSEHk2p1FuodBDbhmWWINevDitFBsWMTkZi5BbL8AVTQlLfgkwSCyyqJX
  duration_in_minutes: 15
  create_secret: e6YJn1cKSEHk2p1FuodBDbhmWWINevDitFBsWMTkZi5BbL8AVTQlLfgkwSCryqJX

server_certificate:
  server_cert_file: cert/server-cert.pem
  server_key_file: cert/server-key.pem
  ca_cert_file: cert/ca-cert.pem

client_certificate:
  client_cert_file: cert/client-cert.pem
  client_key_file: cert/client-key.pem
  ca_cert_file: cert/ca-cert.pem

email:
  smtp_server: smtp.com.br
  smtp_secure: ssl/tls
  smtp_port: 465
  pop_server: pop.com.br
  pop_secure: ssl/tls
  pop_port: 995
  imap_server: imap.com.br
  imap_secure: ssl/tls
  imap_port: 993
  user: your@yourdomain.com
  password: gf$@)Bhl#78(k
  account: your@yourdomain.com
  account_name: your