// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: auth.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	VersionOfAuthMicroService(ctx context.Context, in *VersionOfAuthMicroServiceRequest, opts ...grpc.CallOption) (*VersionOfAuthMicroServiceResponse, error)
	LoginById(ctx context.Context, in *LoginByIdRequest, opts ...grpc.CallOption) (*LoginByIdResponse, error)
	LoginByEmail(ctx context.Context, in *LoginByEmailRequest, opts ...grpc.CallOption) (*LoginByEmailResponse, error)
	LoginByPhone(ctx context.Context, in *LoginByPhoneRequest, opts ...grpc.CallOption) (*LoginByPhoneResponse, error)
	LoginByDocument(ctx context.Context, in *LoginByDocumentRequest, opts ...grpc.CallOption) (*LoginByDocumentResponse, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) VersionOfAuthMicroService(ctx context.Context, in *VersionOfAuthMicroServiceRequest, opts ...grpc.CallOption) (*VersionOfAuthMicroServiceResponse, error) {
	out := new(VersionOfAuthMicroServiceResponse)
	err := c.cc.Invoke(ctx, "/iuris.account.v1.Auth/VersionOfAuthMicroService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) LoginById(ctx context.Context, in *LoginByIdRequest, opts ...grpc.CallOption) (*LoginByIdResponse, error) {
	out := new(LoginByIdResponse)
	err := c.cc.Invoke(ctx, "/iuris.account.v1.Auth/LoginById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) LoginByEmail(ctx context.Context, in *LoginByEmailRequest, opts ...grpc.CallOption) (*LoginByEmailResponse, error) {
	out := new(LoginByEmailResponse)
	err := c.cc.Invoke(ctx, "/iuris.account.v1.Auth/LoginByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) LoginByPhone(ctx context.Context, in *LoginByPhoneRequest, opts ...grpc.CallOption) (*LoginByPhoneResponse, error) {
	out := new(LoginByPhoneResponse)
	err := c.cc.Invoke(ctx, "/iuris.account.v1.Auth/LoginByPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) LoginByDocument(ctx context.Context, in *LoginByDocumentRequest, opts ...grpc.CallOption) (*LoginByDocumentResponse, error) {
	out := new(LoginByDocumentResponse)
	err := c.cc.Invoke(ctx, "/iuris.account.v1.Auth/LoginByDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations should embed UnimplementedAuthServer
// for forward compatibility
type AuthServer interface {
	VersionOfAuthMicroService(context.Context, *VersionOfAuthMicroServiceRequest) (*VersionOfAuthMicroServiceResponse, error)
	LoginById(context.Context, *LoginByIdRequest) (*LoginByIdResponse, error)
	LoginByEmail(context.Context, *LoginByEmailRequest) (*LoginByEmailResponse, error)
	LoginByPhone(context.Context, *LoginByPhoneRequest) (*LoginByPhoneResponse, error)
	LoginByDocument(context.Context, *LoginByDocumentRequest) (*LoginByDocumentResponse, error)
}

// UnimplementedAuthServer should be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (UnimplementedAuthServer) VersionOfAuthMicroService(context.Context, *VersionOfAuthMicroServiceRequest) (*VersionOfAuthMicroServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VersionOfAuthMicroService not implemented")
}
func (UnimplementedAuthServer) LoginById(context.Context, *LoginByIdRequest) (*LoginByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginById not implemented")
}
func (UnimplementedAuthServer) LoginByEmail(context.Context, *LoginByEmailRequest) (*LoginByEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginByEmail not implemented")
}
func (UnimplementedAuthServer) LoginByPhone(context.Context, *LoginByPhoneRequest) (*LoginByPhoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginByPhone not implemented")
}
func (UnimplementedAuthServer) LoginByDocument(context.Context, *LoginByDocumentRequest) (*LoginByDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginByDocument not implemented")
}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_VersionOfAuthMicroService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionOfAuthMicroServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).VersionOfAuthMicroService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iuris.account.v1.Auth/VersionOfAuthMicroService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).VersionOfAuthMicroService(ctx, req.(*VersionOfAuthMicroServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_LoginById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).LoginById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iuris.account.v1.Auth/LoginById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).LoginById(ctx, req.(*LoginByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_LoginByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).LoginByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iuris.account.v1.Auth/LoginByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).LoginByEmail(ctx, req.(*LoginByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_LoginByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginByPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).LoginByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iuris.account.v1.Auth/LoginByPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).LoginByPhone(ctx, req.(*LoginByPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_LoginByDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginByDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).LoginByDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iuris.account.v1.Auth/LoginByDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).LoginByDocument(ctx, req.(*LoginByDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iuris.account.v1.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VersionOfAuthMicroService",
			Handler:    _Auth_VersionOfAuthMicroService_Handler,
		},
		{
			MethodName: "LoginById",
			Handler:    _Auth_LoginById_Handler,
		},
		{
			MethodName: "LoginByEmail",
			Handler:    _Auth_LoginByEmail_Handler,
		},
		{
			MethodName: "LoginByPhone",
			Handler:    _Auth_LoginByPhone_Handler,
		},
		{
			MethodName: "LoginByDocument",
			Handler:    _Auth_LoginByDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
